addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
install:
- bundle install --gemfile=./android/Gemfile --path ./android
script:
- "./flutter/bin/flutter test"
- cd android
- fastlane internal
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- mkdir -p ~\/Git/
- openssl aes-256-cbc -K $encrypted_cf9e7a818c63_key -iv $encrypted_cf9e7a818c63_iv
  -in ./android/api-8716197817448099265-38356-0c0516e0c71a.json.enc -out ~\/Git/api-8716197817448099265-38356-0c0516e0c71a.json
  -d
