addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- mkdir -p ~\/Git/
- openssl aes-256-cbc -K $encrypted_c8720522f6b8_key -iv $encrypted_c8720522f6b8_iv
  -in ./android/api-8716197817448099265-38356-0c0516e0c71a.json.enc -out ~\/Git/api-8716197817448099265-38356-0c0516e0c71a.json
  -d
install:
- bundle install --gemfile=./android/Gemfile --path ./android
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
script:
- "./flutter/bin/flutter test"
- cd android
- fastlane internal
